name: OSMPL
version: 1.0.0
description: Utilities for OSM
author: sho
main: dev.shog.osmpl.OsmPl
depend: [Vault, Essentials]

commands:
    plmg:
        description: Player Manager
        permission: osm.plmg
        permission-message: You do not have permission for this!
        usage: /plmg [username]
    osm:
        description: Manage OSM and view OSM version.
        permission: osm.manage
        permission-message: You do not have permission for this!
        usage: /osm [reload]
    discord:
        description: Get the OSM Discord link.
        usage: /discord
    hat:
        description: Set hat your hat.
        permission: osm.hat
        usage: /hat
    donate:
        description: View your donor status
        usage: /donate
    sleeping:
        description: View the current sleeping players.
        usage: /sleeping
    list:
        description: View a list of the current players.
        usage: /list
    staff:
        description: Staff mode.
        permission: osm.staff
        permission-message: You do not have permission for this!
        usage: /staff [view]
    slowmode:
        description: Manage slowmode properties.
        permission: osm.slowmode
        permission-message: You do not have permission for this!
        usage: /slowmode [toggle/temp/set] {interval}
    raffle:
        description: Raffle
        usage: /raffle [buy/view]
    ban:
        description: Ban and IP ban a user.
        usage: /ban [username] {reason}
        permission-message: You do not have permission for this!
        permission: osm.ban
    tempban:
        description: A temporary ban.
        usage: /tempban [username] [time] {reason}
        permission-message: You do not have permission for this!
        permission: osm.tempban
    warnings:
        description: View your warnings.
        usage: /warnings
    unban:
        description: Unban someone.
        usage: /unban [name]
        permission-message: You do not have permission for this!
        permission: osm.unban
    seen:
        description: View a user's playtime and other information.
        usage: /seen [username]
    mod:
        description: Manage moderator's allowed IPs.
        permission: osm.mod
        permission-message: You do not have permission for this!
        usage: /mod [view/remove/add] [name] [ip]
    landmarks:
        description: Landmarks.
        usage: /landmarks [create/remove/landmark name] {landmark name}
    mute:
        description: Mute a player.
        usage: /mute [player name] {reason}
        permission-message: You do not have permission for this!
        permission: osm.mute
    tempmute:
        description: Temporarily mute a player.
        usage: /tempmute [username] [time] {reason}
        permission-message: You do not have permission for this!
        permission: osm.tempmute
    unmute:
        description: Un-Mute a player.
        usage: /unmute [username]
        permission-message: You do not have permission for this!
        permission: osm.unmute
    ptt:
        description: View the players with the top play time.
        usage: /ptt
    baltop:
        description: View the players with the top balance.
        usage: /baltop
    tfm:
        description: Manage a user's trust factor.
        usage: /tfm [view/give/take] (user) {amount}
        permission-message: You do not have permission for this!
        permission: osm.tfm
    vtfp:
        description: View trust factor progress.
        usage: /vtfp [place/break/move/kill]
        permission-message: You do not have permission for this!
        permission: osm.vtfp
    discordlink:
        description: Discord Link
        usage: /discordlink
        aliases:
            - dl
    cursed:
        description: Manage cursed Discord owrds.
        usage: /cursed [add/remove] {word}
        permission-message: You do not have permission for this!
        permission: osm.dl.cursed
    module:
        description: Manage Modules
        usage: /module [enable/disable/refresh] {module name}
        permission-message: You do not have permission for this!
        permission: osm.mm
    savings:
        description: Manage your savings account.
        usage: /savings [withdraw/deposit] {amount}
    banks:
        description: Manage your bank membership.
        usage: /bank [join/transfer]
    xp:
        description: View your XP.
    quests:
        description: View your complete and uncomplete quests.
    rankup:
        description: Rank up.
    rank:
        description: View your rank.
    osmq_debug:
        description: Debug.
    viewpunish:
        description: View a user's punishments
        usage: /viewpunish [user] {filter/index}
        permission-message: You do not have permission for this!
        permission: osm.viewpunish
    warn:
        description: Warn a user
        usage: /warn [user]
        permission-message: You do not have permission for this!
        permission: osm.warn
    disablequests:
        description: Disable quests.
        usage: /disablequests
    rainbow:
        description: Rainbow-ify your name.
        usage: /rainbow
        permission-message: You do not have permission for this!
        permission: osm.rainbow
    particle:
        description: Use particles.
        usage: /particle [particle name]
        permission-message: You do not have permission for this!
        permission: osm.particles
    wild:
        description: Wild.
        usage: /wild
    kdlb:
        description: Kill/death leaderboard.
        usage: /kdlb
    togglestaffmessages:
        description: Toggle staff messages
        usage: /togglestaffmessage
    streak:
        description: View your login streak.
        usage: /streak
    ignorebroadcast:
        description: Ignore the automated broadcasts.
        usage: /ignorebroadcast
    cjm:
        description: Adjust your custom join message.
        usage: /cjm
    clm:
        description: Adjust your custom leave message.
        usage: /clm
    jp:
        description: Joins Plus
        usage: /jp
    searchip:
        description: Search IP
        usage: /searchip [ip]
permissions:
    osm.particles:
        description: Use particles.
        default: op
    osm.rainbow:
        description: Rainbow-ify your name.
        default: op
    osm.warn:
        description: Warn a user
        default: op
    osm.viewpunish:
        description: View a user's punishments
        default: op
    osm.vtfp:
        description: Allow you to view trust factor progress.
        default: op
    osm.tfm:
        description: Allows you to manage user's trust factors.
        default: op
    osm.manage.reload:
        description: Allows you to reload config.
        default: op
    osm.hat:
        description: Use hats.
        default: op
    osm.staff:
        description: Manage staff mode.
        default: op
    osm.slowmode:
        description: Slow mode.
        default: op
    osm.coloredchat:
        description: Use colored chat.
        default: op
    osm.manage:
        description: Manage OSM.
        default: op
    osm.raffle:
        description: Raffle.
        default: op
    osm.ban:
        description: Ban a user.
        default: op
    osm.tempban:
        description: Temporarily ban a user.
        default: op
    osm.sketchyips:
        description: Get warned of sketchy IPs.
        default: op
    osm.bannotify:
        description: Get warned of bans.
        default: op
    osm.unban:
        description: Unban
        default: op
    osm.plmg:
        description: Player Manager
        default: op
    osm.mute:
        description: Use the mute command.
        default: op
    osm.tempmute:
        description: Use the temp-mute command.
        default: op
    osm.unmute:
        description: Use the un-mute command.
        default: op
    osm.mute.avoid:
        description: With this, you cannot be muted.
        default: op
    osm.dl.cursed:
        description: Manage cursed words.
        default: op
    osm.mm:
        description: Manage modules.
        default: op